export const ADD_DECK = 'ADD_DECK';
export const RECEIVE_DECKS_REQUEST = 'RECEIVE_DECKS_REQUEST';
export const RECEIVE_DECKS_SUCCESS = 'RECEIVE_DECKS_SUCCESS';
export const ADD_DECK_REQUEST = 'ADD_DECK_REQUEST';
export const ADD_DECK_SUCCESS = 'ADD_DECK_SUCCESS';
export const ADD_QUESTION_REQUEST = 'ADD_QUESTION_REQUEST';
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS';
